CREATE TABLE IF NOT EXISTS `vehicle_chests` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `vehicle` VARCHAR(50) NOT NULL,
    `portamalas` JSON NOT NULL,
    `last_accessed` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);